---
- name: Install and Configure Nextcloud using Docker
  hosts: all
  become: yes

  vars:
    nextcloud_domain: "{{ nextcloud_domain | default('localhost') }}"
    nextcloud_external_url: "{{ nextcloud_domain }}"
    nextcloud_home: "/nextcloud"  # Update this path
    nextcloud_db_password: "{{ nextcloud_db_password }}"  # Define your DB password
    nextcloud_admin_user: "{{ nextcloud_admin_user }}"    # Define Nextcloud admin username
    nextcloud_admin_password: "{{ nextcloud_admin_password }}"  # Define Nextcloud admin password

  tasks:
    - name: Install general prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
        update_cache: yes
      when: ansible_facts.packages['docker-ce'] is not defined

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: Ensure Python Docker SDK is installed
      pip:
        name: docker
        state: present

    - name: Ensure nextcloud_home directory exists
      file:
        path: "{{ nextcloud_home }}"
        state: directory
        owner: root  # You can change the owner and group as needed
        group: root
        mode: '0755'

    - name: Pull Nextcloud Docker image
      docker_image:
        name: nextcloud:latest
        source: pull

    - name: Create Nextcloud network
      docker_network:
        name: nextcloud-network

    - name: Create and start Nextcloud container
      docker_container:
        name: nextcloud
        image: nextcloud:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"
        volumes:
          - "{{ nextcloud_home }}/apps:/var/www/html/apps"
          - "{{ nextcloud_home }}/config:/var/www/html/config"
          - "{{ nextcloud_home }}/data:/var/www/html/data"
        env:
          MYSQL_PASSWORD: "{{ nextcloud_db_password }}"
          NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
          NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
        networks:
          - name: nextcloud-network

    - name: Retrieve Nextcloud URL
      debug:
        msg: "Visit http://{{ nextcloud_external_url }}:8080 to access Nextcloud"
